version: '3'

services:
  fastapi: &fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    image: indicator_local_fastapi
    container_name: indicator_local_fastapi
    platform: linux/x86_64
    depends_on:
      - redis
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    command: /start

  redis:
      image: redis:7.0.5
      ports:
        - "6379:6379"
    
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: indicator_local_redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    depends_on:
      - redis
